### ISSUE TITLE
Can't Build Due to Missing Dependencies

### ISSUE THREAD

**Issue by brodkin** [SanderKleykens/opendj-template-virtual-attribute-provider#1]
Hey there,

Its doesn't seem that this project can be built anymore due to ForgeRock removing their public repositories. I'm not sure if you're interested in repairing the project, but do you have a compiled JAR available that can be added to the releases?

**Comment by SanderKleykens** [comment]
Hi @brodkin,

Can you try building again after pulling my latest commit? It seems like the OpenDJ dependency is still there, just in a different repository and under a different group id.

**Comment by brodkin** [comment]
It definitely builds now, thanks! I found a post suggesting that ODJ's public maven server had been shuttered for good, but I'm glad you were able to find that.

All of that being well and good, I loaded the JAR to `/opt/opendj/lib/extensions/template-virtual-attribute.jar` and the LDIF to `/opt/opendj/config/schema/99-template-virtual-attribute.ldif` and it barely seems like the server is aware of the extension. 

On startup I see 
```
category=EXTENSIONS severity=NOTICE msgID=org.opends.messages.extension.571 msg=Loaded extension from file '/opt/opendj/lib/extensions/template-virtual-attribute.jar' (build <unknown>, revision <unknown>)
```
 That seems promising, but when I try to add the attribute I get this error:
```
The sub-type "template" is not a recognized type of Virtual Attribute. It
should be one of: collective-attribute-subentries | custom | entity-tag |
entry-dn | entry-uuid | governing-structure-rule | has-subordinates |
is-member-of | member | num-subordinates | password-expiration-time |
password-policy-subentry | structural-object-class | subschema-subentry |
user-defined
```

Any suggestions?
